spring:
  datasource:
    druid:
      db-type: mysql
      url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 600
      filters: stat,wall
shiro:
  loginUrl: /login.html
  unauthorizedUrl: /common/401.html
server:
  port: 80
  session:
    timeout: 1800
mybatis:
  type-aliases-package: com.mdsoft..model